name: bayarea_urbansim
channels:
  - conda-forge
  - udst
dependencies:
  - python=2.7
  - bottle>=0.12
  - matplotlib>=1.3.1 
  - numpy>=1.8.0
  - orca>=1.1
  - pandas>=0.17.0
  - patsy>=0.3.0
  - prettytable>=0.7.2
  - pyyaml>=3.10
  - scipy>=0.13.3
  - simplejson>=3.3
  - statsmodels>=0.8.0
  - toolz>=0.7.0
  - requests>=2.0
  - zbox>=1.2
  - pytables>=3.1.0
  - pandana>=0.3.0
  - pip
  - pip: