name: bayarea_urbansim
channels:
  - conda-forge
  - udst
dependencies:
  - python=3.6
  - bottle
  - flask
  - matplotlib
  - numpy
  - orca
  - pandas
  - patsy
  - prettytable
  - pyyaml
  - scipy
  - scikit-learn
  - simplejson
  - statsmodels
  - toolz
  - requests
  - zbox
  - conda-forge::pytables
  - pygments
  - pandana
  - pip
  - conda-forge::snappy
  - zbox
  - pip:
#    - git+https://github.com/UDST/orca.git@f49398e2a363f8869e14b5218640d8d9c13863a4
#    - git+https://github.com/UDST/pandana.git@8f24b8a1b7539c95b51153e9954f755a7116089b
    - urbansim == 3.1.*
    - urbansim_defaults == 0.2.*
#    - git+https://github.com/UDST/urbansim.git@286e61049ac1e67c7e7a9eec8acecea704b1a332
#    - git+https://github.com/UDST/urbansim_defaults.git@8c95c2a10c5d0bcd1a470a3b636b47d8824e1254
    - git+https://github.com/UDST/orca_test.git@02357bacc6a31e87b1476ff0f5b377a683e0c86a
